// Home
export const ADD_TO_CART = "ADD_TO_CART";
export const NAME_FILTER = "NAME_FILTER";
export const CATEGORY_FILTER = "CATEGORY_FILTER";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";

// Cart
export const INCREMENT_CART_ITEM_COUNT = "INCREMENT_CART_ITEM_COUNT";
export const DECREMENT_CART_ITEM_COUNT = "DECREMENT_CART_ITEM_COUNT";
